export const MUSIC_GENRES = [
  // Popular Genres
  "Pop",
  "Rock",
  "Hip Hop",
  "R&B",
  "Electronic",
  "Jazz",
  "Classical",
  "Country",
  "Blues",
  "Reggae",
  "Folk",
  "Metal",
  "Indie",
  "Alternative",
  "Soul",
  "Funk",

  // Electronic Subgenres
  "House",
  "Techno",
  "Trance",
  "Dubstep",
  "Drum & Bass",
  "Ambient",
  "IDM",
  "Electro",
  "Breakbeat",
  "Hardstyle",
  "Trap",
  "Future Bass",
  "Chillwave",
  "Synthwave",
  "Vaporwave",
  "Lo-fi",
  "EDM",
  "Progressive House",
  "Deep House",

  // Rock Subgenres
  "Alternative Rock",
  "Progressive Rock",
  "Punk Rock",
  "Hard Rock",
  "Soft Rock",
  "Grunge",
  "Post-Rock",
  "Math Rock",
  "Shoegaze",
  "Glam Rock",
  "Psychedelic Rock",
  "Folk Rock",
  "Blues Rock",
  "Indie Rock",
  "Post-Punk",
  "New Wave",

  // Metal Subgenres
  "Heavy Metal",
  "Death Metal",
  "Black Metal",
  "Thrash Metal",
  "Power Metal",
  "Progressive Metal",
  "Doom Metal",
  "Folk Metal",
  "Symphonic Metal",
  "Nu Metal",
  "Metalcore",
  "Deathcore",
  "Industrial Metal",
  "Gothic Metal",
  "Sludge Metal",

  // Jazz Subgenres
  "Bebop",
  "Swing",
  "Fusion",
  "Smooth Jazz",
  "Latin Jazz",
  "Free Jazz",
  "Cool Jazz",
  "Hard Bop",
  "Modal Jazz",
  "Dixieland",
  "Gypsy Jazz",
  "Jazz Funk",

  // Classical Subgenres
  "Baroque",
  "Romantic",
  "Modern Classical",
  "Chamber Music",
  "Opera",
  "Symphony",
  "Concerto",
  "Choral",
  "Minimalism",
  "Contemporary Classical",

  // World Music
  "Afrobeat",
  "Highlife",
  "Soukous",
  "Mbalax",
  "Kizomba",
  "Samba",
  "Bossa Nova",
  "Tango",
  "Flamenco",
  "Bhangra",
  "K-Pop",
  "J-Pop",
  "C-Pop",
  "Bollywood",
  "Traditional Folk",
  "Celtic",
  "Fado",
  "Rai",
  "Gamelan",
  "Klezmer",

  // Urban/R&B Subgenres
  "Contemporary R&B",
  "Neo-Soul",
  "Gospel",
  "Motown",
  "Funk",
  "Disco",
  "New Jack Swing",
  "Hip Hop Soul",
  "Alternative R&B",
  "Trap Soul",

  // Country Subgenres
  "Bluegrass",
  "Country Pop",
  "Outlaw Country",
  "Country Rock",
  "Honky Tonk",
  "Americana",
  "Western Swing",
  "Progressive Country",
  "Country Blues",

  // Experimental/Avant-garde
  "Noise",
  "Drone",
  "Industrial",
  "Experimental",
  "Avant-garde",
  "Art Rock",
  "Post-Industrial",
  "Dark Ambient",
  "Musique Concrète",
  "Microsound",

  // Regional Genres
  "Latin Pop",
  "Latin Rock",
  "Reggaeton",
  "Salsa",
  "Merengue",
  "Bachata",
  "Cumbia",
  "Mariachi",
  "Norteño",
  "Banda",
  "Ranchera",
  "Tropical",

  // Other Genres
  "Gospel",
  "Christian",
  "New Age",
  "Easy Listening",
  "Children's Music",
  "Holiday",
  "Soundtrack",
  "Video Game Music",
  "Jazz Fusion",
  "World Fusion",
  "Progressive",
  "Psychedelic",
  "Acoustic",
  "Instrumental",
  "Vocal",
  "A Cappella",
  "Choral",
  "Orchestral",
  "Brass Band",
  "Marching Band",
];

export const INSTRUMENTS = [
  // String Instruments
  "Piano",
  "Guitar",
  "Violin",
  "Cello",
  "Bass",
  "Harp",
  "Ukulele",
  "Banjo",
  "Mandolin",
  "Sitar",
  "Koto",
  "Erhu",

  // Wind Instruments
  "Flute",
  "Saxophone",
  "Trumpet",
  "Trombone",
  "Clarinet",
  "Oboe",
  "Bassoon",
  "French Horn",
  "Tuba",
  "Recorder",
  "Pan Flute",
  "Didgeridoo",

  // Percussion
  "Drums",
  "Djembe",
  "Bongos",
  "Congas",
  "Xylophone",
  "Marimba",
  "Vibraphone",
  "Tambourine",
  "Triangle",
  "Cymbals",
  "Timpani",

  // Electronic
  "Synthesizer",
  "Drum Machine",
  "Sampler",
  "MIDI Controller",
  "Theremin",

  // Other
  "Vocals",
  "Harmonica",
  "Accordion",
  "Organ",
  "Harpsichord",
  "Lute",
];

export const customStyles = {
  control: (provided: any) => ({
    ...provided,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    borderColor: "rgb(251, 207, 232)",
    boxShadow: "none",
    "&:hover": {
      borderColor: "rgb(236, 72, 153)",
    },
  }),
  option: (provided: any, state: any) => ({
    ...provided,
    backgroundColor: state.isSelected ? "rgb(236, 72, 153)" : "white",
    color: state.isSelected ? "white" : "rgb(55, 65, 81)",
    "&:hover": {
      backgroundColor: state.isSelected
        ? "rgb(236, 72, 153)"
        : "rgb(249, 168, 212)",
      color: state.isSelected ? "white" : "rgb(55, 65, 81)",
    },
  }),
  multiValue: (provided: any) => ({
    ...provided,
    backgroundColor: "rgb(249, 168, 212)",
  }),
  multiValueLabel: (provided: any) => ({
    ...provided,
    color: "rgb(55, 65, 81)",
  }),
  multiValueRemove: (provided: any) => ({
    ...provided,
    color: "rgb(55, 65, 81)",
    "&:hover": {
      backgroundColor: "rgb(236, 72, 153)",
      color: "white",
    },
  }),
};
